vti_encoding:SR|utf8-nl
vti_author:SR|DESKTOP-6FBPU6L\\Dunia
vti_modifiedby:SR|DESKTOP-6FBPU6L\\Dunia
vti_timelastmodified:TR|19 Jan 2022 19:57:36 -0000
vti_timecreated:TR|19 Jan 2022 19:57:36 -0000
vti_cacheddtm:TX|19 Jan 2022 19:57:36 -0000
vti_filesize:IR|5124
vti_extenderversion:SR|6.0.2.5516
vti_backlinkinfo:VX|databasesite/database1_interface/Results/editor/list.asp databasesite/database1_interface/Results/editor/edit.asp databasesite/database1_interface/Results/editor/update.asp databasesite/database1_interface/Results/results_page.asp databasesite/database1_interface/Results/editor/detail.asp
vti_version:SW|6.0.2.5516
